name: Nightly Build

on:
  schedule:
    # Запускать ежедневно в 2:00 UTC (5:00 по МСК)
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and test
        run: ./gradlew --no-daemon clean build
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_23_X64 || '' }}

      - name: Upload test results (опционально)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            build/reports/tests/
            build/test-results/
          retention-days: 7